### ISSUE TITLE
This template is amazing, you are a god amongst men

### ISSUE THREAD

**Issue by vinnyt123** [tobilg/serverless-cubejs#2]
Hey man, I just wanted to say your template is incredible and makes deploying CubeJS to serverless AWS 100x easier. It worked with 0 problems. This should be in the CubeJS documentation!

**Comment by tobilg** [comment]
Thanks @vinnyt123! Happy that the template is useful to you. I notified the CubeJS team in the past already that this exist, if I remember correctly they were considering adding it to the docs, at least as link.
